export const GET_POSTS_STARTED = "GET_POSTS_STARTED";
export const GET_POSTS_SUCCESS = "GET_POSTS_SUCCESS";
export const GET_POSTS_FAILURE = "GET_POSTS_FAILURE";

export const ADD_POST_STARTED = "ADD_POST_STARTED";
export const ADD_POST_SUCCESS = "ADD_POST_SUCCESS";
export const ADD_POST_FAILURE = "ADD_POST_FAILURE";

export const UPDATE_POST_STARTED = "UPDATE_POST_STARTED";
export const UPDATE_POST_SUCCESS = "UPDATE_POST_SUCCESS";
export const UPDATE_POST_FAILURE = "UPDATE_POST_FAILURE";

export const DELETE_POST_STARTED = "DELETE_POST_STARTED";
export const DELETE_POST_SUCCESS = "DELETE_POST_SUCCESS";
export const DELETE_POST_FAILURE = "DELETE_POST_FAILURE";

export const LIKE_POST_STARTED = "LIKE_POST_STARTED";
export const LIKE_POST_SUCCESS = "LIKE_POST_SUCCESS";
export const LIKE_POST_FAILURE = "LIKE_POST_FAILURE";

export const DISLIKE_POST_STARTED = "DISLIKE_POST_STARTED";
export const DISLIKE_POST_SUCCESS = "DISLIKE_POST_SUCCESS";
export const DISLIKE_POST_FAILURE = "DISLIKE_POST_FAILURE";
